### ISSUE TITLE
Rename to eks-quickstart-app-dev

### ISSUE THREAD

**Issue by dholbach** [weaveworks/eks-quickstart-app-dev#14]
Apparently @kalbir said in some meeting we want to change the repository name to `eks-quickstart-app-dev`. Is this still the case? We will want to reflect this in the docs then.

/cc @gemagomez @martina-if

**Comment by cPu1** [comment]
@dholbach correct, there's an issue open in the aws-workstream repo: https://github.com/weaveworks/aws-workstream/issues/77

**Comment by dholbach** [comment]
Thanks @cPu1
