### ISSUE TITLE
Podinfo's helmrelease is broken

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eks-quickstart-app-dev#24]
I am getting the following error from the Helm Operator when running `eksctl gitops apply --quick-profile app-dev` (current master version of eksctl):

```
ts=2019-09-05T06:35:59.539485198Z caller=release.go:217 component=release error="Chart release failed: podinfo: &status.statusError{Code:2, Message:\"YAML parse error on podinfo/templates/ingress.yaml: error converting YAML to JSON: yaml: line 16: did not find expected alphabetic or numeric character\", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}"
```

This used to work one week ago, so I guess it broke at https://github.com/weaveworks/eks-quickstart-app-dev/commit/bb218b72614623bf52e1f94082f0017bd9cc921e

@marccarre I am going to revert that latest change, since it's blocking me.

**Comment by marccarre** [comment]
Yes, apologies for the inconvenience. Reverting, as per 62964a6cb00ae23923f484d658ed8b9a9ca401d4, was the right thing to do.
