### ISSUE TITLE
Bump HelmRelease resources to stable API version

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eks-quickstart-app-dev#6]
All `HelmRelease`s are using the beta API version `flux.weave.works/v1beta1` but the Flux Helm Operator version (`0.10.1`) installed as part of `eksctl install flux` supports the stable API resource `helm.fluxcd.io/v1`.

**Comment by stefanprodan** [comment]
The Helm Operator 0.10.1 is on `flux.weave.works/v1beta1` and the helm-op 1.0.0-rc1 is on `helm.fluxcd.io/v1`.

**Comment by stefanprodan** [comment]
We have released the stable API today please see https://github.com/fluxcd/helm-operator/releases
